Adding argument for metadata indexing by generate_inputs
khanlab/snakebids pull request #367
Opened 2024-01-31 21:41 UTC by myousif9

Adding argument for metadata indexing with pybids in `generate_inputs` function which allows metadata to be accessible in `BIDSLayout` returned from `<generate_inputs_return>.layout`.

2024-02-01 14:58 UTC, pvandyken requested changes
The repo will need to be formatted with `ruff`, `poetry run poe fix` should do the trick.

Otherwise, looks good

2024-02-01 17:16 UTC, myousif9 commented on snakebids/tests/test_generate_inputs.py
> +from distutils import extension
I'm not sure where they came from, I don't remember using those imports. Though it appears those new imports disappeared after running ruff formatting.

2024-02-01 17:22 UTC, pvandyken commented
@myousif9 feel free to add an ignore comment to the ruff error you're getting

2024-02-01 17:23 UTC, myousif9 commented
Ran ruff formatting.

2024-02-01 18:23 UTC, myousif9 commented
Added ignore comment for ruff error, synced with main branch and now passes all tests.

2024-02-02 17:09 UTC, kaitj approved these changes

2024-02-02 21:14 UTC, pvandyken approved these changes

2024-02-02 21:15 UTC, merged