add is_url() check before checking if is relative path
khanlab/snakebids pull request #452
Opened 2024-07-18 21:59 UTC by Karl5766

## Proposed changes

Related to issue #451, UPath object does not support os.path.is_abs() or .is_absolute() interfaces due to relative vs. absolute paths are not conceptually defined for network locations. This commit changes test for relative path by making sure UPath objects are not tested on whether they are relative path or not.

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [ √ ] Changes have been tested to ensure that fix is effective or that a feature works.
- [ ] Changes pass the unit tests
- [ √ ] I have included necessary documentation or comments (as necessary)
- [ √ ] Any dependent changes have been merged and published

2024-07-19 14:27 UTC, pvandyken requested changes
Other than the comments, this is good, thanks!

2024-07-19 14:27 UTC, pvandyken commented on snakebids/core/input_generation.py
> +    if path.startswith(("file://", "local://")):
When these get read in by the `_is_url(...) and not Path(...)`, they'll break (they won't appear to be absolute).

The absolute check below is really just to make sure that `sub-XXX` is not the very first part of the path, because we need a `/` character before `sub`. This isn't an issue with urls.

I would say just treat anything with a `scheme://` at the beginning as a URL, regardless of whether the scheme is `file`.

2024-07-19 14:27 UTC, pvandyken commented on snakebids/tests/test_generate_inputs.py
> +            assert not _is_url(Path(path))
If you're willing to have a go at hypothesis, could you expand the `TestParseBidsPath` tests to potentially include schemes?

As a hint, basically I would add a new parameter `scheme` with a text strategy filling it with any [valid URI character] (https://stackoverflow.com/questions/1547899/which-characters-make-a-url-invalid#1547940) except for `:/\`, or with `None` (something like `st.text(...) | st.none()`). If `None`, don't prepend a scheme, otherwise prepend the scheme with a valid separator. The test should then work the same either way.

2024-07-19 14:27 UTC, pvandyken commented on snakebids/core/input_generation.py
> +    if path.startswith(("file://", "local://")):
With this change, we don't actually need this function. Just inline the relevant bit and expand the `TestParseBidsPath` class as discussed below.

2024-07-19 14:28 UTC, pvandyken commented
The test failures were popping up on the nightly, they're nothing to do with this PR. I'll have to investigate when I get a chance, don't worry about fixing them in this PR

2024-07-22 14:37 UTC, Karl5766 commented on snakebids/core/input_generation.py
> +    if path.startswith(("file://", "local://")):
`_is_url(...) and not Path(...)` tests if the path is a relative path, but looking at [wiki](https://en.wikipedia.org/wiki/File_URI_scheme) I think "file:///path" can be both relative or absolute depending on what follows the "file:///" prefix. I'm keeping the _is_url() function as a interface (non-duplicated definition of what's a url).

If we treat `scheme://` as URL, then windows path `C://` or Posix `c:\\` will be treated as URL, which defeats the purpose. Are "file:///" and "local://" paths currently supported? If not, maybe we treat them as unsupported types until they are needed in the future. With this I will remove the above two lines testing specifically for them.

2024-07-22 19:11 UTC, Karl5766 commented on snakebids/tests/test_generate_inputs.py
> +            assert not _is_url(Path(path))
I see the synthetic bids path functions currently accept a `root: Path | None = None` parameter that defaults to the current `"."` path, but how do I combine it with paths generated from a `path()` strategy?

2024-07-22 19:59 UTC, Karl5766 commented
Just updated the PR for the changes in above 2 comments. There may be issues as mentioned so let me know what you think.

2024-07-23 00:16 UTC, pvandyken commented on snakebids/tests/test_generate_inputs.py
> +            assert not _is_url(Path(path))
Ah, I see, I wouldn't worry about the root. What we care about testing is the scheme `scheme://`, because that's the feature that's not currently possible that your pull request enables. So from my perspective, I wouldn't make a new composite strategy, but something like this:

```py
    @given(
		component=sb_st.bids_components(max_values=1, restrict_patterns=True),
		scheme=st.text(st.characters(...)) | st.none(), # just use valid scheme characters here
	)
    def test_splits_wildcards_from_path(self, component: BidsComponent, scheme: str | None):
        path = component.expand()[0]
		if scheme is not None:
			path = f"{scheme}://{path}"
        ...
```

I think something like that should do the trick.

2024-07-23 00:17 UTC, pvandyken commented on snakebids/tests/test_generate_inputs.py
> +            assert not _is_url(Path(path))
I guess technically we could expand the `bid_components()` strategy to potentially produced paths with schemes, but since it's really just this one function affected, I don't see a ton of utility right now for the extra complexity it creates

2024-07-23 01:51 UTC, Karl5766 commented on snakebids/tests/test_generate_inputs.py
> +            assert not _is_url(Path(path))
Just pushed a commit to fix this

2024-07-23 19:47 UTC, pvandyken requested changes
Left another round of comments, but it's coming together!

2024-07-23 19:47 UTC, pvandyken commented on snakebids/tests/strategies.py
> +def schemes() -> st.SearchStrategy[str | None]:
It's best to have a strategy return one type of thing. So have this just return strings, then when you use it, you would mix it with a `None` strategy

2024-07-23 19:47 UTC, pvandyken commented on snakebids/tests/strategies.py
> +    prefix_st: st.SearchStrategy[str | None] = None,  # for urls e.g. "gs://..."
Can we instead just treat schemes the way we treat absolute? So have a `scheme: bool | None` parameter, defaults to `None`. If `None`, it may or may not add a scheme. If false, it doesn't, if true, it does. This will help make sure schemes are tested wherever we use paths.

2024-07-23 19:47 UTC, pvandyken commented on snakebids/tests/strategies.py
> +    if prefix_st:
This builds on the above comment, but for the interaction with `absolute`, only complain if the user specifies incompatible options like `scheme=True`, `absolute=True`. If one or both are `None`, just implicitly set the other as needed

2024-07-23 19:47 UTC, pvandyken commented on snakebids/core/input_generation.py
> +        not _is_network_fs_path(path)
So I still don't understand why we care about network paths specifically in this function. The function isn't actually reading the url, it's parsing it as a string. And the only reason we had the relative path check before is that we can't have `sub-whatever` as the very first thing in the path, because the regex expects a slash first `/sub-whatever`. So so long as we start with any kind of scheme (even `c//` or `C:\\`), we should be fine?

2024-07-23 19:47 UTC, pvandyken commented on snakebids/core/input_generation.py
> +    elif not _is_network_fs_path(pybidsdb_dir) and not Path(pybidsdb_dir).is_absolute():
Will pybids be able to read network paths for the **database**, even with your PR? If so this is fine, but otherwise I don't care to build support for something that doesn't work in pybids anyway.

2024-07-23 19:47 UTC, pvandyken commented on snakebids/tests/strategies.py
> +    fixed = st.sampled_from(["C://", "c:\\", "gs://", "s3://"])
Can you make the letters (`gs`, `s3` etc) random? So draw something from the `text` strategy.

2024-07-23 19:47 UTC, pvandyken commented on snakebids/tests/test_generate_inputs.py
> +    if sys.version_info[:2] >= (3, 12):
It's best to split this off into a separate test, and use `pytest.mark.skipif` (there's some examples in this codebase, and also easy to find online).

You needn't test every example with the subclass, one will suffice.

2024-07-23 19:47 UTC, pvandyken commented on snakebids/tests/test_generate_inputs.py
> +    test_data = (
My preference is to make tests as small and granular as possible. With that in mind, these examples should be run using `@pytest.mark.parametrize`.

2024-07-23 19:47 UTC, pvandyken commented on snakebids/tests/test_generate_inputs.py
> +def scheme_bids_component_strategy(draw, **kwargs):
Make sure this gets removed if its not being used

2024-07-23 19:51 UTC, pvandyken commented on snakebids/core/input_generation.py
> +    if path.startswith(("file://", "local://")):
Just left another comment related, but to close this off, I think the confusion might be coming because snakebids generally doesn't care about schemes at all. What this PR is addressing is a pretty small technicality relating to how we parsed paths before. We really just need to check that the very first character in the path is not part of an entity. But if we have `anything://` at the beginning, we know for sure that's not an entity. So I was questioning why `file://` was getting treated specially.

Windows support is a bit of another fish. I don't mind adding code to support drive letters, but until we actually run tests on a windows image on github, we don't promise any windows support. Not really a priority right now because almost all apps realistically are on either linux, WSL, or some docker image.

2024-07-23 21:45 UTC, Karl5766 commented on snakebids/core/input_generation.py
> +        not _is_network_fs_path(path)
For this one, "gs://" will be converted to "gs:/" that's not supported by gcsfs, that's really the only issue here

2024-07-23 21:46 UTC, Karl5766 commented on snakebids/core/input_generation.py
> +    elif not _is_network_fs_path(pybidsdb_dir) and not Path(pybidsdb_dir).is_absolute():
Can you point me to docs about paths with databases? I'm not particularly well versed in this topic.

2024-07-23 21:51 UTC, Karl5766 commented on snakebids/core/input_generation.py
> +    elif not _is_network_fs_path(pybidsdb_dir) and not Path(pybidsdb_dir).is_absolute():
Ah I see what you mean, I'll just remove this line

2024-07-24 00:32 UTC, Karl5766 commented on snakebids/tests/strategies.py
> +    fixed = st.sampled_from(["C://", "c:\\", "gs://", "s3://"])
Mostly I want to avoid issues that some file schemes behave differently than others (`file` can be `file:/`, `file://` or `file:///` and may be either local or mapped from network), so only test on a fixed set of schemes. I guess this PR is really asking for a `is_local_relative` function that tests if a path is a relative path to the current working directory. Should I change `is_network_fs_path` to this `is_local_relative` function?
```
def _is_network_fs_path(path: Path | str):
    return not bool(urlparse(str(path)).netloc) and not os.path.isabs(path)
```

2024-07-25 12:16 UTC, pvandyken requested changes

2024-07-25 12:16 UTC, pvandyken commented on snakebids/tests/test_generate_inputs.py
> +        scheme=sb_st.schemes(),
I think this and the others need the `st.none()` strategy as well, otherwise

2024-07-25 12:16 UTC, pvandyken commented on snakebids/core/input_generation.py
> +        not _is_network_fs_path(path)
So that's what I'm concerned about. Right now (as per my tests), `file:///...` be converted into `file:/...`? That's also undesirable, no? Whereas `file://...` will be preserved.

2024-07-25 12:20 UTC, pvandyken commented on snakebids/tests/strategies.py
> +    fixed = st.sampled_from(["C://", "c:\\", "gs://", "s3://"])
Yeah, so I think testing of Windows Paths works best on a windows system. In that case, Python automatically uses the `WindowsPath`, which handles drives correctly. As I mentioned previously, I'm okay with testing windows drive here, but until we actually run the test suite on a windows system, we don't officially support windows

2024-07-25 12:29 UTC, pvandyken commented
I think there's still some confusion in the comments, so I'm going to try to lay everything here again as best as I can to make sure we're both talking about the same thing.

The problem in this PR is that certain paths are getting mangled by the `generate_inputs` function, particularly any path with a network scheme (e.g. `scheme://`). This is because the `_parse_bids_path` uses `pathlib.Path` to do some normalization, and these removes any doubled or tripled slashes. This normalization is done to ensure `sub-XXX` is not the very first thing in the path.

So to fix this, we add a function that detects if such a scheme is being used, and if so, we don't do any path normalization. This leaves the path intact. In general, any path with double or more slashes should not be modified. The semantic meaning of the slashes or the scheme is unimportant, we just don't want to change it. The path will then be passed transparently to the `BidsComponent`, where the user can apply it appropriately.

Does this seem like an accurate summary?

2024-07-25 14:41 UTC, Karl5766 commented
Yes this does summarizes and clarifies things. i've pushed new commits to address these issues, so please take a look if available

2024-07-25 18:38 UTC, pvandyken approved these changes
Looks great! We can merge as soon as all the checks are passing. I'm going to get #453 merged first, so you'll be able to rebase onto that

2024-07-25 18:41 UTC, pvandyken commented
When fixing the quality checks, do you mind squashing your changes into a single commit with a description of the fix?

2024-07-25 18:44 UTC, pvandyken commented
Just merged #453, so you can go ahead and rebase that as well

2024-07-25 18:46 UTC, Karl5766 commented
> When fixing the quality checks, do you mind squashing your changes into a single commit with a description of the fix?

That is squashing the previous 7 commits if I understand it right? Sure then

2024-07-26 12:18 UTC, pvandyken commented
> That is squashing the previous 7 commits if I understand it right? Sure then

The 7 commits.

2024-07-26 15:11 UTC, Karl5766 commented
I'm leaving a `schemed_paths()` function in strategies.py due to return type issue, but note the function is not called anywhere. @pvandyken Can you merge the PR if everything looks good?

2024-07-27 15:39 UTC, merged

2024-07-29 14:03 UTC, pvandyken commented
Thanks. Never got a chance to ask, but what is the purpose of keeping `schemed_paths()` around? I'd rather not keep a function that's never being used.

2024-07-29 14:08 UTC, Karl5766 commented
Sorry I thought you asked me to add scheme to paths strategy, but upon rereading the comments that's not the case. Yeah you can remove it since it's unused.